name: "Update MS Windows versions dictionary"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Crawl versions
        shell: pwsh
        run: |
          [Void](New-Item -Path "lists" -ItemType Directory -ErrorAction SilentlyContinue -Confirm:$False)
          .\Get-WindowsServerBuildsList.ps1 | ConvertTo-Json -Depth 10 | Out-File -Force -Confirm:$false -FilePath lists\ms-windows-server-versions.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic update